### ISSUE TITLE
ERROR: Exception while generating and saving resource spreadsheet. 1

### ISSUE THREAD

**Issue by Danielosama** [GreyHak/dsp-csv-gen#1]
Pretty much title, I get that error in the log every time I try to generate the csv file.

**Comment by koza1258** [comment]
I have exactly the same error.
Isn't it a problem with write permissions to the file?
@GreyHak 
Could you build a version that logs the error that occurs while saving?

**Comment by GreyHak** [comment]
@Danielosama and @koza1258 , thank you so much for the feedback.  I've pushed an update which (a) adds a config file for the user to control the path of the output spreadsheet, and (b) enhances the exception text.  I've tested this version with paths which were read-only and nonexistent, and received detailed error messages in both those cases.  v1.1.0 should fix your issues.  Please let me know if you're satisfied with the correction or if you're still having issues.  Thank you!

**Comment by koza1258** [comment]
ERROR: DirectoryNotFoundException while generating and saving resource spreadsheet: Could not find a part of the path `"C:\Users\TEST\Documents\DSP_Star_Sector_Resources.csv".`

So I already know the problem
In my case, I have transferred the document from c: to d:
So the path should be:`"D:\Documents\DSP_Star_Sector_Resources.csv".`

You are getting bad environment variable of the directory "Documents" from user.
90% of your solution will work. But I'm in the 10% :)
`Environment.ExpandEnvironmentVariables(@"%USERPROFILE%\Documents\" + spreadsheetFileName);`

**Comment by koza1258** [comment]
A better approach would be to use this method instead of the current one
`Environment.GetFolderPath( Environment.SpecialFolder.MyDocuments+ spreadsheetFileName );`

`Environment.GetFolderPath(@"%USERPROFILE%\Documents\" + spreadsheetFileName);`

**Comment by GreyHak** [comment]
@koza1258 Great suggestion.  I'll roll that into the next release.  Thank you.

**Comment by GreyHak** [comment]
Resolved in v1.1.0 and v1.1.3
