### ISSUE TITLE
Add revolution & rotation speed to the CSV

### ISSUE THREAD

**Issue by araishikeiwai** [GreyHak/dsp-csv-gen#11]
Hi there!

I'd like to thank you first for the great mod! I could plan which system to visit.

However, it'll be nice if we have each of the planets' revolution & rotation speed. Might not be useful essentially, but it's nice to see the variance in the game.

I was on a planet in a black hole system and it rotated at 89 seconds. How the stars in the sky moved so fast amazed me.
Then there's also a 6th planet with 40 thousands seconds of revolution speed. Imagine the length of the summer/winter for your poles.

**Comment by GreyHak** [comment]
@araishikeiwai Thank you for the feedback.  I'll add the parameters if they're easily accessable.  You might need to enable them in the config file so we don't clutter the output.

**Comment by GreyHak** [comment]
@araishikeiwai 14 additional parameters are now configurabily enableable in release v3.0.1.

**Comment by araishikeiwai** [comment]
thanks for this! I'll try it tonight
