### ISSUE TITLE
Doesn't generate the file. 

### ISSUE THREAD

**Issue by SketchInInk** [GreyHak/dsp-csv-gen#14]
The button is present. But after I press it it shows like a quarter of circumference of progress and stops. No file in the destination folder.

**Comment by SketchInInk** [comment]
﻿[Message:   BepInEx] BepInEx 5.4.5.0 - DSPGAME
[Info   :   BepInEx] Running under Unity v2018.4.12.5889476
[Info   :   BepInEx] CLR runtime version: 2.0.50727.1433
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [DSP Star Sector Resource Spreadsheet Generator 3.0.1.0]
[Info   :DSP Star Sector Resource Spreadsheet Generator] Will use spreadsheet path "E:\LLL\Docs\DSP_Star_Sector_Resources_${seed}-${starCount}.csv"
[Info   :DSP Star Sector Resource Spreadsheet Generator] Initialization complete.
[Info   :   BepInEx] Loading [Copy Inserters Plug-In 1.6.0.0]
[Message:   BepInEx] Chainloader startup complete
[Info   :DSP Star Sector Resource Spreadsheet Generator] Planet loaded.
[Info   :DSP Star Sector Resource Spreadsheet Generator] Planet loaded.
[Info   :DSP Star Sector Resource Spreadsheet Generator] Planet loaded.
[Info   :DSP Star Sector Resource Spreadsheet Generator] Planet loaded.
[Info   :DSP Star Sector Resource Spreadsheet Generator] Game beginning
[Info   :DSP Star Sector Resource Spreadsheet Generator] Planet modeling reset is not needed.
[Info   :DSP Star Sector Resource Spreadsheet Generator] Planet loaded.
[Info   :DSP Star Sector Resource Spreadsheet Generator] Planet loaded.
[Info   :DSP Star Sector Resource Spreadsheet Generator] Planet loaded.
[Info   :DSP Star Sector Resource Spreadsheet Generator] Planet loaded.
[Info   :DSP Star Sector Resource Spreadsheet Generator] Game beginning
[Info   :DSP Star Sector Resource Spreadsheet Generator] Loading button
[Info   :DSP Star Sector Resource Spreadsheet Generator] Button load complete
[Info   :DSP Star Sector Resource Spreadsheet Generator] Scanning planets...
[Info   :DSP Star Sector Resource Spreadsheet Generator] 191 planets to be loaded.  Waiting for planets to load.
[Info   :DSP Star Sector Resource Spreadsheet Generator] Planet loaded.
[Info   :DSP Star Sector Resource Spreadsheet Generator] Planet loaded.
[Info   :DSP Star Sector Resource Spreadsheet Generator] Planet loaded.
[Info   :DSP Star Sector Resource Spreadsheet Generator] Planet loaded.
[Info   :DSP Star Sector Resource Spreadsheet Generator] Planet loaded.
[Info   :DSP Star Sector Resource Spreadsheet Generator] Planet loaded.
[Info   :DSP Star Sector Resource Spreadsheet Generator] Planet loaded.
[Info   :DSP Star Sector Resource Spreadsheet Generator] Planet loaded.

**Comment by GreyHak** [comment]
Thank you for the report @SketchInInk .  This is broken for me too.  I think an update was pushed for the core game which is causing my background thread not to start.  I'll try to solve it this evening.

**Comment by GreyHak** [comment]
@SketchInInk An update with a fix will be out no later than tonight.
Last night the game changed.  This mod's planet loading thread uses the parameter PlanetData.reformMaterial which has changed in the core game to PlanetData.reformMaterial0 and PlanetData.reformMaterial1.  This is preventing the thread routine from starting.
Thank you again for bringing this to my attention.

**Comment by SketchInInk** [comment]
> @SketchInInk An update with a fix will be out no later than tonight.
> Last night the game changed. This mod's planet loading thread uses the parameter PlanetData.reformMaterial which has changed in the core game to PlanetData.reformMaterial0 and PlanetData.reformMaterial1. This is preventing the thread routine from starting.
> Thank you again for bringing this to my attention.

Good to hear that you already know the reason. Thank you for your good job.

**Comment by GreyHak** [comment]
@SketchInInk   Issue fixed in release v3.0.2.
