### ISSUE TITLE
Distance from the starting star

### ISSUE THREAD

**Issue by d7urban** [GreyHak/dsp-csv-gen#15]
The generated file is very useful! In my file I added a column for distance from home star, using the formula =ROUND(SQRT($E2*$E2+$F2*$F2+$G2*$G2),2)
Maybe something to add?

**Comment by GreyHak** [comment]
Nice idea @d7urban .  Thank you.  I'll add it as a configurable output in the next release.

**Comment by GreyHak** [comment]
This enhancement has been pushed to GitHub for inclusion in the next release.

**Comment by GreyHak** [comment]
@d7urban This feature has been included in release v3.0.3.
