### ISSUE TITLE
Path denied

### ISSUE THREAD

**Issue by NZ-Wanderer** [GreyHak/dsp-csv-gen#16]
Seem to have a little problem in that the file is refusing to save to my drives...

The path in the config is: M:\DSP_Star_Sector_Resources_${seed}-${starCount}.csv
I get this in the log: [Info   :DSP Star Sector Resource Spreadsheet Generator] ERROR: UnauthorizedAccessException while generating and saving resource spreadsheet: Access to the path "M:\" is denied.

I changed the path to my I:
So now the path in the config is: I:\DSP_Star_Sector_Resources_${seed}-${starCount}.csv
And I got this in the log: [Info   :DSP Star Sector Resource Spreadsheet Generator] ERROR: UnauthorizedAccessException while generating and saving resource spreadsheet: Access to the path "I:\" is denied.

**Comment by GreyHak** [comment]
@Simpy Are you having an issue if you use a path that clearly won't be unauthorized?  Have you tried just not specifying a path?  There's not much I can do about access denied, but if I can, I'll try to help.

**Comment by NZ-Wanderer** [comment]
My M: might be a problem as it is where my Documents files and folders are kept, but the I: is just a general drive... By not specifying a path do you mean just leave that line in the config empty? (BTW this is NZ_Wanderer from discord)

**Comment by GreyHak** [comment]
@Simpy Could you try something simple, let setting it to "resources.csv".  If that works, I'd recommend trying something that isn't in the root of the drive.

**Comment by NZ-Wanderer** [comment]
I uninstalled the mod, wiped the leftover config files, reinstalled, did not go into the config and it seems to have worked, it saved it to "m:\My Documents\" so your guess of not in root could have been the cause.. :)
Thank you for your help
