### ISSUE TITLE
No config file

### ISSUE THREAD

**Issue by alfons234** [GreyHak/dsp-csv-gen#17]
Hi,
just tried to give your mod a try. I could create a .csv file in my documents folder, that was the easy part. But due to the fact that the separators are commas and my local format also uses commas the spreadsheet is quite a mess, and replacing the commas by tabs, well, it replaces all commas of course.

The actually bug is that there is no config file of your mod. There are only the BepInEx.cfg and two other files from the 4th of March, when i picked up the game again.
Any insight if it is incompatible with other mods?

Greetings and keep up the work !

[BepInEx.txt](https://github.com/GreyHak/dsp-csv-gen/files/6121112/BepInEx.txt)

**Comment by GreyHak** [comment]
@alfons234 Did you install the mod manually, by using r2modman, or some other mod manager?  Are you on Windows or Linux?  If you're on Windows...
 - If you installed manually:  `%PROGRAMFILES(X86)%\Steam\steamapps\common\Dyson Sphere Program\BepInEx\config\greyhak.dysonsphereprogram.resourcespreadsheetgen.cfg`
 - If you installed with r2modman:  `C:\Users\<username>\AppData\Roaming\r2modmanPlus-local\DysonSphereProgram\profiles\Default\BepInEx\config\greyhak.dysonsphereprogram.resourcespreadsheetgen.cfg`

**Comment by alfons234** [comment]
Yeah, thanks, I found it.
Well, found folders of rodman under roaming, local and the steamapp, several different folders each. What a mess.
But good work on your part, I appreciate it.
Thanks !
