### ISSUE TITLE
[Feature Request] Add Columns

### ISSUE THREAD

**Issue by Simrien** [GreyHak/dsp-csv-gen#19]
This is very useful for tracking resource usage over time and determining where specific resources and what quantity is located on which planet at a glance.

Please could you also add the following columns;
Star Temperature
Star Radius
Star Distance (from the home system)

We have the coordinates and it's a simple matter to calculate the star distances from 0,0,0.
I use the following formula to calculate the distance from the home system; Distance=SQRT(X^2+Y^2+Z^2).

**Comment by GreyHak** [comment]
@Simrien These data points are already supported by the mod, they're just optional.  Please update the config to enable StarTemperature, StarRadius and DistanceFromStarClusterCenter.

**Comment by Simrien** [comment]
You star @GreyHak, RTFM clearly. Thank you.
