### ISSUE TITLE
Update broke mod

### ISSUE THREAD

**Issue by posi74de** [GreyHak/dsp-csv-gen#20]
Seems like todays update made the mod stop working: I was able to generate spreadsheets before work today and when I came back a DSP update was rolled out via steam. Since then generating a sheet does not work anymore: indicator circle goes to ~25% ASAP and stays there forever... would be cool to have this great mod working again!

**Comment by GreyHak** [comment]
@posi74de I am unable to reproduce your issue.  Please confirm that you're using the latest v3.1.2.  If you're on the latest version, please attach your Dyson Sphere Program\BepInEx\LogOutput.log produced after experiencing the problem.  Thank you.

**Comment by posi74de** [comment]
Just got a game update to 0.7.18.7103 and tried again - no luck.
Yes, I'm using 3.1.2 ... Here are my steps to reproduce:

- start r2modman (details see screenshot)
- start modded (with  BepInEx 5.4.5)
- start new game, seed 11969842 / 64 stars
- land on planet, click spreadsheet icon

Result: circle goes to ~20% and stays there forever. Waited 5 mins and took screen as attached. Log file also attached.

![2021-06-08 16_21_28-r2modman - Default](https://user-images.githubusercontent.com/54323984/121205951-5bfefb80-c878-11eb-8557-8b7ed901a79d.png)
![2021-06-08 16_32_51-Greenshot](https://user-images.githubusercontent.com/54323984/121205961-5dc8bf00-c878-11eb-909c-aa936ebd153c.png)
[LogOutput.log](https://github.com/GreyHak/dsp-csv-gen/files/6617449/LogOutput.log)

**Comment by GreyHak** [comment]
Thank you @posi74de .  I have reproduced the bug.  It appears only when I create or load a new game, not when I load an old one.  I'll look into it this evening.

**Comment by GreyHak** [comment]
@posi74de I've put out v3.1.3 to fix this problem, but it's incomplete.  The hanging has been fixed.  However, the hanging was caused by a new ocean type, and I don't know what it is.  So the spreadsheet will have a placeholder.  Can you fly to different planets in a newly generated world?  If so, please let me know what the new ocean type is.  The new output will tell you what planet(s) have the new ocean type.  Thank you.

**Comment by Anyndil** [comment]
New Ocean Type is **Ice**.
Which makes sense. It looks like it only occurs on _Scarlet Ice Lake_ Planet Types.

`Zeta Crucis III,Zeta Crucis,1.139,A type star,-3.72333734900585,-3.38362923429618,-14.9180586570953,0.7,0.85,Scarlet Ice Lake,0.7147348,"None",??? Please let me know what ocean type is on this planet with a comment...`

![image](https://user-images.githubusercontent.com/20710045/121289546-1ad80d00-c8b3-11eb-96eb-090ab2db79d0.png)

**Comment by posi74de** [comment]
I can confirm both - spread sheet is generating again and ocean type as Ice. Thanks for the quick solution - I'm happy to generate sheets again!

**Comment by GreyHak** [comment]
Thank you @posi74de .  "Ice" has been added to v3.1.4.
