### ISSUE TITLE
ThreadFlag protection Level

### ISSUE THREAD

**Issue by tng88** [GreyHak/dsp-csv-gen#23]
Not sure which update changed the protection level of the ThreadFlag enum but since your last update it was change to private.

'PlanetModelingManager.ThreadFlag' is inaccessible due to its protection level	
DSPResourceSpreadsheetGenMod	...\DSPSpreadsheetGenMod.cs	92	Active

Other elements also had the protection levels changed.

**Comment by GreyHak** [comment]
@tng88 I just did an export using the mod's latest v3.2.1 version on the game version 0.8.22.9331, and I didn't have any issues.  Are you having trouble with the released binaries?  Or is your issue only when building the source code on your own?

**Comment by tng88** [comment]
I was trying to build the source code on my own.

**Comment by GreyHak** [comment]
@tng88 I'm happy to help with instructions on building v3.2.1 on your own.  The key component you need is the older Assembly-CSharp.ref.dll which is available on Google Drive.  I got it through a Discord link posted by Windows10CE.  I'll likely need to move to the newer method in the next build, but that's what the baseline is using now.  The file is https://docs.google.com/uc?export=download&id=1vhvu9yr6NiVFDpKb9Iou8iQVkC4lrLXQ  If you would like further instructions, please let me know.
