### ISSUE TITLE
PlanetModelingManager.EndPlanetComputeThread() not found in Assembly-CSharp.dll

### ISSUE THREAD

**Issue by alexzhuustc** [GreyHak/dsp-csv-gen#28]
Download the dsp-csv-gen v4.0.0 and run it. Works as expected. It's a great mod.

However when I try to build this plugin from source, I failed to compile it. 
After copying Assembly-CSharp.dll from DSP game version=0.9.26.13034. Visual Studio keeps complaint it cannot find the private variable/method defined in PlanetModelingManager. The snapshot is below.
![private_access](https://user-images.githubusercontent.com/1658550/188669757-7be13be0-b038-4fcf-92cb-ba2d47ce12ff.png)

I noticed "_Copy_DLLs_Here.bat" says download Assembly-CSharp.refstub.dll from Google Drive。 I tried, but the downloaded version of DLL this still failed to build. Some of the variables are missing。 For example: ```planet.calculated```

Is there any hint to build the code from source？

**Comment by GreyHak** [comment]
@alexzhuustc Thank you for pointing out that the note in _Copy_DLLs_Here.bat is no longer accurate.  I've updated the file to point at https://nuget.bepinex.dev/packages/DysonSphereProgram.GameLibs

**Comment by alexzhuustc** [comment]
It works now, thanks a lot!

Also realized anyone can make similar assembly via https://github.com/BepInEx/NStrip tool
