### ISSUE TITLE
Combined Memory Issue

### ISSUE THREAD

**Issue by Dorky106** [GreyHak/dsp-csv-gen#3]
Not really an issue with the mod but when used with Touhma's Galactic Scale mod, this mod will ramp up to extreme levels of memory usage.  I'm set to use 1024 systems, the game slowly slows right down after loading into the game and uses up all 16GBs of memory I have.
So may want to put a note about this.

**Comment by GreyHak** [comment]
Thank you for the feedback @Dorky106 .  I'm updating the README now to add a note.  Then I'll look into what I might be able to do to avoid this.

**Comment by Dorky106** [comment]
Already have a half-baked fix you want to use it.

So I grabbed a copy of your code. Made 1 little edit, got it working a bit.
if ((planet.loaded) && (planet.type != EPlanetType.Gas) && (planet.veinGroups.Length == 0))
I just check if the system is loaded or not.
So maybe a fix would be to add to the config to see if the players only want the loaded systems?

**Comment by GreyHak** [comment]
@Dorky106 Great suggestion.  I'll add a config option.
FYI: In my if statement the (planet.veinGroups.Length == 0) check is a better check for whether the planet load needs to be requested.  Don't ask me why, but that's what the testing showed.

**Comment by GreyHak** [comment]
In order to implement the enhancement described in this ticket, two bugs in the original game needed to be corrected.  v1.3.0 included bug fixes for those problems in the original game.

**Comment by GreyHak** [comment]
@Dorky106 Star Sector Resource Spreadsheet Generator v2.0.0 now minimizes memory usage.  So it should work much better with Touhma's Galactic Scale mod, even when loading planet resource data.  Please let me know if you have any issues with this update.  Thank you.

**Comment by GreyHak** [comment]
@Dorky106 I've put out a v3.0.0-beta to speed up planet loading while still being able to play the game and with low memory overhead.  If you're interesting, I would appreciate any beta test feedback, especially with the Touhma's Galactic Scale mod.  You can at me on Discord, or post to Issues here on GitHub.  https://github.com/GreyHak/dsp-csv-gen/releases/tag/v3.0.0-beta

**Comment by Dorky106** [comment]
I have it running.  WIll get back to you on the rough time it takes to finish it.
I test it right from the start of a new game to be safe.
