### ISSUE TITLE
[suggestion] Parameterize output filename

### ISSUE THREAD

**Issue by ctcDNightmare** [GreyHak/dsp-csv-gen#7]
Just a quick showerthought: It would be nice to be able to have some information directly in the output filename.

Most useful example, the [seed + galaxy size](https://i.imgur.com/k10anC3.png) (and maybe even resource modifier?)
And have that configurable like the *io.ryen.scheduledsave* mod does it for inserting the count in the save-name.
Ex. ```SpreadsheetFileName = g:\dsp-seeds\$seed$-$size$-$resources$.csv```

**Comment by GreyHak** [comment]
@ctcDNightmare I like the idea.  I'd like to make some tweaks to your proposed solution.

**Comment by GreyHak** [comment]
@ctcDNightmare Released in v2.0.1.  Note that the formatting has been changed.  I'm a big Linux user, and this is the formatting that would be used on Linux.  Thank you again for the contribution!
