### ISSUE TITLE
[2.0.0] File is no longer being generated.

### ISSUE THREAD

**Issue by Chalos-Atiesh** [GreyHak/dsp-csv-gen#9]
Only have this and BepInEx installed. The output file is no longer being generated when starting a new game.
Saving to the default location.
Seed: 77468472
LoadAllPlanets: true
UnloadPlanets: true
SaveOnStart: true
SaveOnPause: true
Output: default

**Comment by Chalos-Atiesh** [comment]
Well maybe not. I stepped away for a minute and came back to the file. Maybe it's just a performance regression and taking longer to generate than previously.

**Comment by GreyHak** [comment]
@Chalos-Atiesh Yes, the mod is slower now.  It was a compromise to dramatically save on memory usage.  Trigger button should be showing you progress, so you can get confirmation that the generation is actively progressing.

If you don't care about memory usage, I could update the mod to be faster again so long as UnloadPlanets is set to false.

**Comment by Chalos-Atiesh** [comment]
I think that's a reasonable compromise. Generally I don't care about memory usage since I enable the mod when I'm using it and disable it when I'm not. When I'm using it I'm not actively playing the game and just waiting on the file to be generated. However I can see some (most) users leaving it enabled all the time. Giving an opt-in option to tell the mod 'I don't care about memory usage' would be nice.

**Comment by GreyHak** [comment]
@Chalos-Atiesh If you disable the two triggers in the config file, and use the trigger button on the HUB instead, there shouldn't be any need to disable the mod when not in use.
I'm having a little trouble with setting UnloadPlanets=false to speed up generation.  The reason the game slowed down was because queuing all those planets caused a problem if you wanted to warp to another star that was at the bottom of the queue.  Unloading made the problem so bad that I needed to accept the speed compromise, but the issue exists even when not unloading.  Sorry, we're going to have to live with the trade off of slower generation so that planets show up when you warp to them.

**Comment by Chalos-Atiesh** [comment]
@GreyHak I realize the issue. Even experienced it myself once but I figured that was the cause. So I didn't do that again. I'm also not saying to roll back the optimization so planets load when you warp to them. Just maybe a feature that says 'No, I do not care about memory usage or planets not loading when I warp to them because I will not be warping to any planets.' Probably with a disclaimer in the description. Said feature is off by default to not impact the regular use case. Then people like me who scout tons and tons of star seeds are do not have to wait ~5 minutes for the sheet to generate for every star system.

Overall I agree that, for the average person, the experience is vastly better with the throttling. However I have a bad habit of not being the average user.

**Comment by newt111** [comment]
I second being able to turn this off. I only ever use the mod on a new game, then disable it after I find a good system.

**Comment by GreyHak** [comment]
@Chalos-Atiesh @newt111 I've put out a v3.0.0-beta to speed up planet loading while still being able to play the game and with low memory overhead.  If you're interesting, I would appreciate any beta test feedback.  You can at me on Discord, or post to Issues here on GitHub.  https://github.com/GreyHak/dsp-csv-gen/releases/tag/v3.0.0-beta

**Comment by Chalos-Atiesh** [comment]
@GreyHak Dunno how you did it but that's _massively_ better. Fist pass and no issues. I'll keep poking at it. Great job!
